<a href="https://colab.research.google.com/github/Atakan-Topaloglu/Blockchain-Presentation/blob/master/Blockchain.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import hashlib
import numpy as np
from pprint import pprint   # optional, can be used instead of np

In [32]:
msg1 = hashlib.sha256()
msg1.update(b"I seek the Holy Grail")
hex_message_1 = msg1.hexdigest
print(f'Hexadecimal representation of the first hash is: \n {hex_message_1()}\n')

msg2 = hashlib.sha256()
msg2.update(b"I seek the Poly Grail")
hex_message_2 = msg2.hexdigest
print(f'Hexadecimal representation of the second hash is: \n {hex_message_2()}')

Hexadecimal representation of the first hash is: 
 a09c2b84ed466a5021e370a4219eec3abdba83c211d01b9208fd5b60fa2c7628

Hexadecimal representation of the second hash is: 
 2f1d32667a803e4d5d9c7afe6732c865f7d4f49d95e766807e8bf9eff95169eb




---


Looking at the outputs above, we can see that even if a single character
of the input string changes, the hex code of the hash is altered dramatically. This indicates (but does not prove) that **SHA 256** outputs seemingly random values where knowing the hash of a certain input doesn't provide valuable information about closely related strings.


---

In [ ]:
def pretty_print(string):
  row = ""
  for i in range(2, len(string)):
    row += string[i] + " "
    if (i-1)%16 == 0:
      print(row)
      row = ""

In [ ]:
int_msg_1 = int(hex_message_1(), base=16)
binary_msg_1 = bin(int_msg_1)


print("SHA-256 for the first message:\n")
pretty_print(binary_msg_1)
print("\n")

int_msg_2 = int(hex_message_2(), base=16)
binary_msg_2 = bin(int_msg_2)

print("SHA-256 for the second message: \n")
pretty_print(binary_msg_2)


SHA-256 for the first message:

1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 
0 0 1 0 1 0 1 1 1 0 0 0 0 1 0 0 
1 1 1 0 1 1 0 1 0 1 0 0 0 1 1 0 
0 1 1 0 1 0 1 0 0 1 0 1 0 0 0 0 
0 0 1 0 0 0 0 1 1 1 1 0 0 0 1 1 
0 1 1 1 0 0 0 0 1 0 1 0 0 1 0 0 
0 0 1 0 0 0 0 1 1 0 0 1 1 1 1 0 
1 1 1 0 1 1 0 0 0 0 1 1 1 0 1 0 
1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 0 
1 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 
0 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 
0 0 0 1 1 0 1 1 1 0 0 1 0 0 1 0 
0 0 0 0 1 0 0 0 1 1 1 1 1 1 0 1 
0 1 0 1 1 0 1 1 0 1 1 0 0 0 0 0 
1 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 
0 1 1 1 0 1 1 0 0 0 1 0 1 0 0 0 


SHA-256 for the second message: 

1 0 1 1 1 1 0 0 0 1 1 1 0 1 0 0 
1 1 0 0 1 0 0 1 1 0 0 1 1 0 0 1 
1 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 
1 1 1 1 1 0 0 1 0 0 1 1 0 1 0 1 
0 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 
1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 1 
1 0 0 1 1 1 0 0 1 1 0 0 1 0 1 1 
0 0 1 0 0 0 0 1 1 0 0 1 0 1 1 1 
1 1 0 1 1 1 1 1 0 1 0 1 0 0 1 1 
1 1 0 1 0 0 1 0 0 1 1 1 0 1 1 0 
0 1 0 1 0 1 1 1 1 0 0 1 1 1 0 1 
1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 
1 1 1 1 

In [ ]:
def str_to_list(string):
  rows = []
  row = []
  for i in range(2, len(string)):
    row.append(int(string[i]))
    if (i-1)%16==0:
      rows.append(row)
      row = []
  return rows

# to visualize the extent of difference of hashes, let's build an xor_calculator 
# that outputs x xor y for each element of list_1 and list_2 where x is an element
# of list_1 and y is an element of list_2

def xor_calc(list_1, list_2):
  values = []
  for row in range(15):
    value = list(map(lambda x, y: x^y, list_1[row], list_2[row]))
    values.append(value)
    value = []
  return values

In [ ]:
msg1_list = str_to_list(binary_msg_1)
msg2_list = str_to_list(binary_msg_2)

msg_diff_1_2 = xor_calc(msg1_list, msg2_list)
np_diff = np.array(msg_diff_1_2)


print('Difference between binary representations of hashes is:\n')
print(np_diff)

Difference between binary representations of hashes is:

[[0 0 0 1 1 1 0 0 1 1 1 0 1 0 0 0]
 [1 1 1 0 0 0 1 0 0 0 0 1 1 1 0 1]
 [0 0 0 0 0 1 1 1 0 1 0 0 0 1 1 0]
 [1 0 0 1 0 0 1 1 0 1 1 0 0 1 0 1]
 [0 1 0 1 0 1 1 1 1 0 0 1 0 0 1 0]
 [1 0 0 1 1 0 1 1 0 1 0 1 1 1 0 1]
 [1 0 1 1 1 1 0 1 0 1 0 1 0 1 0 1]
 [1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 1]
 [0 1 1 0 0 0 1 0 1 1 1 0 1 0 0 1]
 [0 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 0 1 0 0 1 1 0 1]
 [1 0 0 0 0 0 0 1 1 0 0 1 0 0 1 1]
 [1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0]
 [1 0 1 1 1 1 0 0 1 1 0 1 1 1 1 1]
 [0 0 0 1 1 1 1 1 0 1 1 0 1 0 0 1]]
